[general]
live_config_reload = true
working_directory = "None"
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin/catppuccin-macchiato.toml",
  # "~/.config/alacritty/catppuccin/catppuccin-mocha.toml"
  "~/.config/alacritty/gruvbox/themes/gruvbox_material_hard_dark.toml",
]

[env]
TERM = "xterm-256color"
WINIT_HIDPI_FACTOR = "1.25"
WINIT_UNIX_BACKEND = "wayland"

[keyboard]
bindings = [{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" }]

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
# ref_test = false
render_timer = false

[font]
# AppleFontSmoothing = true
size = 16.0
normal = { family = "BlexMono Nerd Font" }

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"

[window]
dimensions = { columns = 80, lines = 25 }
decorations = "full"
dynamic_padding = false
dynamic_title = false
opacity = 1.0
startup_mode = "Windowed"

[window.padding]
x = 4
y = 4

[terminal.shell]
program = "tmux"
